import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeftSideBar } from "../_components/Leftside-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="bg-[#F4F4F5] h-screen flex gap-5">
        <LeftSideBar />
        <div className="flex flex-col overflow-scroll w-full ">
          <div className="px-10">{children}</div>
        </div>
      </div>
    </>
  );
}
